# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket  = "slopwell-sandbox-tfstate"
    encrypt = true
    key     = "slopwell-sandbox/alb/terraform.tfstate"
    region  = "ap-northeast-1"
  }
}
