# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket  = "slopwell"
    encrypt = true
    key     = "slopwell-sandbox/aws/iam/terraform.tfstate"
    region  = "ap-northeast-1"
  }
}
