// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.
import type { ResourcesConfig } from "aws-amplify";

export const config: ResourcesConfig = {
  API: {
    GraphQL: {
      endpoint:
        "https://ox2tbjzzrbettdhvmgt6lljh3a.appsync-api.ap-northeast-1.amazonaws.com/graphql",
      region: "ap-northeast-1",
      defaultAuthMode: "apiKey",
      apiKey: "da2-sgl6tkj6tzgsjlkz5gtvopheva",
    },
  },
};
